<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Forum\Module'                              => __DIR__ . '/Module.php',
  'Forum\Factory\ForumTableFactory'           => __DIR__ . '/src/Forum/Factory/ForumTableFactory.php',
  'Forum\Factory\PostControllerFactory'       => __DIR__ . '/src/Forum/Factory/PostControllerFactory.php',
  'Forum\Factory\IndexControllerFactory'      => __DIR__ . '/src/Forum/Factory/IndexControllerFactory.php',
  'Forum\Model\ForumTable'                    => __DIR__ . '/src/Forum/Model/ForumTable.php',
  'Forum\Controller\Plugin\NormalizeCategory' => __DIR__ . '/src/Forum/Controller/Plugin/NormalizeCategory.php',
  'Forum\Controller\Plugin\NormalizeTopic'    => __DIR__ . '/src/Forum/Controller/Plugin/NormalizeTopic.php',
  'Forum\Controller\IndexController'          => __DIR__ . '/src/Forum/Controller/IndexController.php',
  'Forum\Controller\PostController'           => __DIR__ . '/src/Forum/Controller/PostController.php',
  'Forum\Form\ForumForm'                      => __DIR__ . '/src/Forum/Form/ForumForm.php',
  'Forum\Form\ForumFormFilter'                => __DIR__ . '/src/Forum/Form/ForumFormFilter.php',
);
