<?php
// Generated by Zend Framework 2
return array(
    'Forum\Module'                         => __DIR__ . '/Module.php',
    'Forum\Factory\ForumTableFactory'  => __DIR__ . '/src/Forum/Factory/ForumTableFactory.php',
    'Forum\Factory\IndexControllerFactory' => __DIR__ . '/src/Forum/Factory/IndexControllerFactory.php',
    'Forum\Model\ForumTable'           => __DIR__ . '/src/Forum/Model/ForumTable.php',
    'Forum\Controller\IndexController'     => __DIR__ . '/src/Forum/Controller/IndexController.php',
    'Forum\Form\TopicFormFilter'           => __DIR__ . '/src/Forum/Form/TopicFormFilter.php',
    'Forum\Form\TopicForm'                 => __DIR__ . '/src/Forum/Form/TopicForm.php',
);