<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'QandA\Module'                            => __DIR__ . '/Module.php',
  'QandA\Model\Data'                        => __DIR__ . '/src/QandA/Model/Data.php',
  'QandA\Controller\IndexController'        => __DIR__ . '/src/QandA/Controller/IndexController.php',
  'QandA\Controller\IndexControllerFactory' => __DIR__ . '/src/QandA/Controller/IndexControllerFactory.php',
  'QandA\Form\SearchForm'                   => __DIR__ . '/src/QandA/Form/SearchForm.php',
  'QandA\Form\SearchFilter'                 => __DIR__ . '/src/QandA/Form/SearchFilter.php',
  'QandATest\Framework\TestCase'            => __DIR__ . '/tests/QandA/Framework/TestCase.php',
  'QandATest\SampleTest'                    => __DIR__ . '/tests/QandA/SampleTest.php',
);
