<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RouteTest\Module'                     => __DIR__ . '/Module.php',
    'RouteTest\Entity\Storage'             => __DIR__ . '/src/RouteTest/Entity/Storage.php',
    'RouteTest\Controller\IndexController' => __DIR__ . '/src/RouteTest/Controller/IndexController.php',
);
