<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2f\Module'                     => __DIR__ . '/Module.php',
    'Zf2f\Controller\IndexController' => __DIR__ . '/src/Zf2f/Controller/IndexController.php',
    'Zf2f\Helper\ListLinks'           => __DIR__ . '/src/Zf2f/Helper/ListLinks.php',
);
