<h1>Route Test -- <?php echo $this->name; ?></h1>
<ul>
<li><a href="<?php echo $this->url('routetest-hostname'); ?>">routetest-hostname</a></li>
<li><a href="<?php echo $this->url('routetest-query'); ?>">routetest-query</a></li>
<li><a href="<?php echo $this->url('routetest-query/query', array('a' => 'A')); ?>">routetest-query/query</a></li>
<li><a href="<?php echo $this->url('routetest-query/query', array('a'=> 'A', 'b' => 'B', 'c' => 'C')); ?>">routetest-query/query, array('a'=> 'A', 'b' => 'B', 'c' => 'C')</a></li>
<li><a href="<?php echo $this->url('routetest-wildcard/wildcard', array('a'=> 'A', 'b' => 'B', 'c' => 'C')); ?>">routetest-wildcard, array('a'=> 'A', 'b' => 'B', 'c' => 'C')</a></li>
</ul>
<hr />
<form method="POST">
<input type="text" name="name" value="NAME TEST" />
<input type="submit" />
</form>