<?php
// Generated by Zend Framework 2
return array(
    'ClassFile\Module'                         => __DIR__ . '/Module.php',
    'ClassFile\Factory\ClassFileTableFactory'  => __DIR__ . '/src/ClassFile/Factory/ClassFileTableFactory.php',
    'ClassFile\Factory\IndexControllerFactory' => __DIR__ . '/src/ClassFile/Factory/IndexControllerFactory.php',
    'ClassFile\Model\ClassFileTable'           => __DIR__ . '/src/ClassFile/Model/ClassFileTable.php',
    'ClassFile\Controller\IndexController'     => __DIR__ . '/src/ClassFile/Controller/IndexController.php',
);