<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FormDemo\Module'                           => __DIR__ . '/Module.php',
  'FormDemo\Factory\TableServiceFactory'      => __DIR__ . '/src/FormDemo/Factory/TableServiceFactory.php',
  'FormDemo\Factory\CityFormFactory'          => __DIR__ . '/src/FormDemo/Factory/CityFormFactory.php',
  'FormDemo\Factory\EditCityFormFactory'      => __DIR__ . '/src/FormDemo/Factory/EditCityFormFactory.php',
  'FormDemo\Service\TableService'             => __DIR__ . '/src/FormDemo/Service/TableService.php',
  'FormDemo\Entity\ListingsEntity'            => __DIR__ . '/src/FormDemo/Entity/ListingsEntity.php',
  'FormDemo\Controller\ApplicationController' => __DIR__ . '/src/FormDemo/Controller/ApplicationController.php',
  'FormDemo\Controller\ReportController'      => __DIR__ . '/src/FormDemo/Controller/ReportController.php',
  'FormDemo\Controller\IndexController'       => __DIR__ . '/src/FormDemo/Controller/IndexController.php',
  'FormDemo\Controller\AnnotationController'  => __DIR__ . '/src/FormDemo/Controller/AnnotationController.php',
  'FormDemo\Controller\DropDownsController'   => __DIR__ . '/src/FormDemo/Controller/DropDownsController.php',
  'FormDemo\Form\EditCityForm'                => __DIR__ . '/src/FormDemo/Form/EditCityForm.php',
  'FormDemo\Form\CityForm'                    => __DIR__ . '/src/FormDemo/Form/CityForm.php',
  'FormDemoTest\Framework\TestCase'           => __DIR__ . '/tests/FormDemo/Framework/TestCase.php',
  'FormDemoTest\SampleTest'                   => __DIR__ . '/tests/FormDemo/SampleTest.php',
);
