<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FormDemo\Module'                        => __DIR__ . '/Module.php',
    'FormDemo\Controller\IndexController' => __DIR__ . '/src/FormDemo/Controller/IndexController.php',
    'FormDemoTest\Framework\TestCase'        => __DIR__ . '/tests/FormDemo/Framework/TestCase.php',
    'FormDemoTest\SampleTest'                => __DIR__ . '/tests/FormDemo/SampleTest.php',
);
