<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ServiceManagerDemo\Module'                        => __DIR__ . '/Module.php',
    'ServiceManagerDemo\Controller\IndexController' => __DIR__ . '/src/ServiceManagerDemo/Controller/IndexController.php',
    'ServiceManagerDemoTest\Framework\TestCase'        => __DIR__ . '/tests/ServiceManagerDemo/Framework/TestCase.php',
    'ServiceManagerDemoTest\SampleTest'                => __DIR__ . '/tests/ServiceManagerDemo/SampleTest.php',
);
