<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ServiceManagerDemo\Module'                       => __DIR__ . '/Module.php',
  'ServiceManagerDemo\Factory\DemoAbstractFactory'  => __DIR__ . '/src/ServiceManagerDemo/Factory/DemoAbstractFactory.php',
  'ServiceManagerDemo\Factory\DontInitializeMe'     => __DIR__ . '/src/ServiceManagerDemo/Factory/DontInitializeMe.php',
  'ServiceManagerDemo\Factory\DelegatorDemoFactory' => __DIR__ . '/src/ServiceManagerDemo/Factory/DelegatorDemoFactory.php',
  'ServiceManagerDemo\Factory\DemoFactory'          => __DIR__ . '/src/ServiceManagerDemo/Factory/DemoFactory.php',
  'ServiceManagerDemo\Service\DemoTest'             => __DIR__ . '/src/ServiceManagerDemo/Service/DemoTest.php',
  'ServiceManagerDemo\Service\DelegatorDemoService' => __DIR__ . '/src/ServiceManagerDemo/Service/DelegatorDemoService.php',
  'ServiceManagerDemo\Model\DemoModel'              => __DIR__ . '/src/ServiceManagerDemo/Model/DemoModel.php',
  'ServiceManagerDemo\Controller\IndexController'   => __DIR__ . '/src/ServiceManagerDemo/Controller/IndexController.php',
  'ServiceManagerDemoTest\Framework\TestCase'       => __DIR__ . '/tests/ServiceManagerDemo/Framework/TestCase.php',
  'ServiceManagerDemoTest\SampleTest'               => __DIR__ . '/tests/ServiceManagerDemo/SampleTest.php',
);
