<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CacheDemo\Module'                     => __DIR__ . '/Module.php',
  'CacheDemo\Controller\IndexController' => __DIR__ . '/src/CacheDemo/Controller/IndexController.php',
  'CacheTest\Framework\TestCase'         => __DIR__ . '/tests/Cache/Framework/TestCase.php',
  'CacheTest\SampleTest'                 => __DIR__ . '/tests/Cache/SampleTest.php',
);
