<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PhpUnit\Module'                        => __DIR__ . '/Module.php',
    'PhpUnit\Controller\IndexController' => __DIR__ . '/src/PhpUnit/Controller/IndexController.php',
    'PhpUnitTest\Framework\TestCase'        => __DIR__ . '/tests/PhpUnit/Framework/TestCase.php',
    'PhpUnitTest\SampleTest'                => __DIR__ . '/tests/PhpUnit/SampleTest.php',
);
