<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'SimpleAuth\Module'                          => __DIR__ . '/Module.php',
  'SimpleAuth\Plugin\LoggedInControllerPlugin' => __DIR__ . '/src/SimpleAuth/Plugin/LoggedInControllerPlugin.php',
  'SimpleAuth\Plugin\LoggedInViewHelper'       => __DIR__ . '/src/SimpleAuth/Plugin/LoggedInViewHelper.php',
  'SimpleAuth\Model\User'                      => __DIR__ . '/src/SimpleAuth/Model/User.php',
  'SimpleAuth\Controller\IndexController'      => __DIR__ . '/src/SimpleAuth/Controller/IndexController.php',
  'SimpleAuth\Form\LoginForm'                  => __DIR__ . '/src/SimpleAuth/Form/LoginForm.php',
  'SimpleAuth\Form\LoginFilter'                => __DIR__ . '/src/SimpleAuth/Form/LoginFilter.php',
  'SimpleAuthTest\Framework\TestCase'          => __DIR__ . '/tests/SimpleAuth/Framework/TestCase.php',
  'SimpleAuthTest\SampleTest'                  => __DIR__ . '/tests/SimpleAuth/SampleTest.php',
);
