<h1>Route Test -- <?php echo $this->name; ?></h1>
<ul>
<li><a href="<?php echo $this->url('route-test-hostname'); ?>">route-test-hostname</a></li>
<li><a href="<?php echo $this->url('route-test-query'); ?>">route-test-query</a></li>
<li><a href="<?php echo $this->url('route-test-query/query', array('a' => 'A')); ?>">route-test-query/query</a></li>
<li><a href="<?php echo $this->url('route-test-query/query', array('a'=> 'A', 'b' => 'B', 'c' => 'C')); ?>">route-test-query/query, array('a'=> 'A', 'b' => 'B', 'c' => 'C')</a></li>
<li><a href="<?php echo $this->url('route-test-wildcard/wildcard', array('a'=> 'A', 'b' => 'B', 'c' => 'C')); ?>">route-test-wildcard, array('a'=> 'A', 'b' => 'B', 'c' => 'C')</a></li>
</ul>
<hr />
<form method="POST">
<input type="text" name="name" value="NAME TEST" />
<input type="submit" />
</form>