<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cache\Module'                        => __DIR__ . '/Module.php',
    'Cache\Controller\IndexController' => __DIR__ . '/src/Cache/Controller/IndexController.php',
    'CacheTest\Framework\TestCase'        => __DIR__ . '/tests/Cache/Framework/TestCase.php',
    'CacheTest\SampleTest'                => __DIR__ . '/tests/Cache/SampleTest.php',
);
