<div style="width: 300px; float left; display: inline-block; margin: 10px; vertical-align: top;">
<h1>Welcome!</h1>
<hr />
The source code for this website is now posted here:
<br />
<a href="https://github.com/dbierer/zf2.unlikelysource.org" target="_blank">https://github.com/dbierer/zf2.unlikelysource.org</a>
<hr />
Here is a summary of the demo modules current running:
<table>
<tr>
<td><h3>CheckOrder</h3></td>
<td>
<ul>
<li>Demonstrates what happens when the same ServiceManager key "check-test" is configured in:
	<ul>
	<li>config/autoload/local.php</li>
	<li>module/CheckOrder/config/module.config.php</li>
	<li>module/CheckOrder/Module.php</li>
	</ul>
	This module also shows events and listeners configured in the Module.php file, using
	the init() and onBootStrap() methods.
	</li>
</ul>
</td>
</tr>
<tr>
<td><h3>RouteTest</h3></td>
<td>
Demonstrates the following routes:
<ul>
<li>hostname</li>
<li>query</li>
<li>wildcard</li>
</ul>
</td>
<td>
</td>
</tr>
<tr>
<td><h3>Forum</h3></td>
<td>Module which implements a simple forum with categories and topics.
<br />Shows solutions to lab specific to various classes which have been running over the past several months.
</td>
</tr>
<tr>
<td><h3>ViewTest</h3></td>
<td>
Demonstrates the following techniques:
<ul>
<li>Custom view helpers</li>
<li>Order and values</li>
<li>JSON strategy</li>
</ul>
</td>
<td>
</td>
</tr>
</table>
</div>
<div style="width: 300px; float right; display: inline-block; margin: 10px;">
<img src="/images/shopping_centre_tunnel_edinburgh.jpg" width=300px />
</div>
