<h1>Welcome!</h1>
<hr />
The source code for this website is now posted here:
<a href="https://github.com/dbierer/zf2-demo-modules" target="_blank">https://github.com/dbierer/zf2-demo-modules</a>
<hr />
Here is a summary of the demo modules current running:
<table>
<tr><th><h2>Module</h2></th><th><h2>Description</h2></th></tr>
<tr>
<td><h3>CheckOrder</h3></td>
<td>
<ul>
<li>Demonstrates what happens when the same ServiceManager key "check-test" is configured in:
	<ul>
	<li>config/autoload/local.php</li>
	<li>module/CheckOrder/config/module.config.php</li>
	<li>module/CheckOrder/Module.php</li>
	</ul>
	This module also shows events and listeners configured in the Module.php file, using
	the init() and onBootStrap() methods.
	</li>
</ul>
</td>
</tr>
<tr>
<td><h3>RouteTest</h3></td>
<td>
Demonstrates the following routes:
<ul>
<li>hostname</li>
<li>query</li>
<li>wildcard</li>
</ul>
</td>
<td>
</td>
</tr>
<tr>
<td><h3>Forum</h3></td>
<td>Module which implements a simple forum with categories and topics.
<br />Shows solutions to lab specific to various classes which have been running over the past several months.
</td>
</tr>

</table>