<h1>Zend Framework 2 Fundamentals</h1>
<hr />
<div style="float: left; width: 150px;">
<h2>Class Notes</h2>
<?php echo $this->listLinks($this->config['class'], '/zf2f/class'); ?>
</div>
<div style="float: left; width: 50px;">
&nbsp;
</div>
<div style="float: left; width: 500px;">
<h2>Lab Notes</h2>
<?php echo $this->listLinks($this->config['notes'], '/zf2f/lab/notes'); ?>
<h2>Lab Solutions</h2>
<?php echo $this->listLinks($this->config['solutions'], '/zf2f/lab/solutions'); ?>
</div>
